spring:
  application:
    name: moms
  datasource:
    url: jdbc:postgresql://localhost:5432/Moms
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  security:
    secret: dPm0sj-aH7uinrw6kehVHML0TLTVldDgDRfnrhSkXdI
  lifetime: 300m
